<a href="https://colab.research.google.com/github/alfonsoamt/Curso-Pandas-y-Numpy/blob/main/Curso_B%C3%A1sico_de_Manipulaci%C3%B3n_y_Transformaci%C3%B3n_de_Datos_con_Pandas_y_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  **¿Por qué NumPy y Pandas?**

## **¿Por qué NumPy?**
Es una librería enfocada al cálculo númerico y manejo de Arrays.
* Es muy veloz, hasta 50 veces más rápido que usar una lista de Python o C.
* Optimiza el almacenamiento en memoria.
* Además, maneja distintos tipos de datos.

Es una librería muy poderosa, se pueden crear redes neuronales desde cero.

## **¿Por qué Pandas?**

Pandas está enfocada a la manipulación y análisis de datos.
* Al estar construido sobre NumPy veloz.
* Requiere poco código para manipular los datos.
* Soporta múltiples formatos de archivos.
* Ordena los datos en una alienación inteligente.

Se pueden manejar grandes cantidades de datos, hacer analítica y crear dahsboards.

La forma de importar estas librerías es de la siguiente manera:


```
import numpy as np
import pandas as pd
```



In [1]:
import numpy as np
import pandas as pd

## **NumPy Array**
El array es el principal objeto de la librería. Representa datos de manera estructurada y se puede acceder a ellos a traves del indexado, a un dato específico o un grupo de muchos datos específicos.

In [2]:
lista = [1, 2 , 3, 4, 5, 6, 7, 8, 9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
arr = np.array(lista)

In [4]:
type(arr)

numpy.ndarray

In [6]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# El indexado nos permite acceder a los elementos de los array y matrices
# Los elementos se emepiezan a contar desde 0.
arr[0]

1

In [8]:
# Es posible operar directamente con los elementos.
arr[0] + arr[5]

7

In [9]:
# En el caso de las matrices al indezar una posición se regresa el array de dicha posición.
matriz[0]

array([1, 2, 3])

In [10]:
# Para seleccionar un solo elemento de la matriz se especifica la posición del elemento separada por comas.
matriz[0, 2]

3

In [11]:
# El slicing nos permite extraer varios datos, tiene un comienzo y un final.
# En este ejemplo se está extrayendo datos desde la posición 1 hasta la 5. [1:6].
arr[1:6]

array([2, 3, 4, 5, 6])

In [12]:
# Si no se ingresa el valor de Start se toma el incio como la posición 0.
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [13]:
# En cambio si no se le da una posción de End se regresan todos los elementos hasta el final del array.
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
# También se puede trabajar por pasos.
# En este ejemplo de 3 en 3.
arr[::3]
# Regresa la posición 0, 0 + 3, 3 + 3 y como no hay posición 6 + 3, no se regrese nada.

array([1, 4, 7])

In [15]:
# Cuando se le asigna un valor negativo se regresan los valores comenzando desde la última posición del array.
arr[-1]

9

In [16]:
arr[-3:]

array([7, 8, 9])

In [17]:
# Para el caso de las matrices sucede algo similar.
# Para acceder a los valores a nivel de filas.
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [18]:
# Para acceder a los valores a nivel de filas y columnas.
matriz[1:, 0:2]

array([[4, 5],
       [7, 8]])