<a href="https://colab.research.google.com/github/alfonsoamt/Curso-Pandas-y-Numpy/blob/main/Curso_B%C3%A1sico_de_Manipulaci%C3%B3n_y_Transformaci%C3%B3n_de_Datos_con_Pandas_y_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  **🤓 ¿Por qué NumPy y Pandas?**

## **🔢¿Por qué NumPy?**
Es una librería enfocada al cálculo númerico y manejo de Arrays.
* Es muy veloz, hasta 50 veces más rápido que usar una lista de Python o C.
* Optimiza el almacenamiento en memoria.
* Además, maneja distintos tipos de datos.

Es una librería muy poderosa, se pueden crear redes neuronales desde cero.

## **🐼¿Por qué Pandas?**

Pandas está enfocada a la manipulación y análisis de datos.
* Al estar construido sobre NumPy veloz.
* Requiere poco código para manipular los datos.
* Soporta múltiples formatos de archivos.
* Ordena los datos en una alienación inteligente.

Se pueden manejar grandes cantidades de datos, hacer analítica y crear dahsboards.

La forma de importar estas librerías es de la siguiente manera:


```
import numpy as np
import pandas as pd
```



In [117]:
import numpy as np
import pandas as pd

## **🔢NumPy Array**
El array es el principal objeto de la librería. Representa datos de manera estructurada y se puede acceder a ellos a traves del indexado, a un dato específico o un grupo de muchos datos específicos.

In [118]:
lista = [1, 2 , 3, 4, 5, 6, 7, 8, 9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [119]:
arr = np.array(lista)

In [120]:
type(arr)

numpy.ndarray

In [121]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [122]:
# El indexado nos permite acceder a los elementos de los array y matrices
# Los elementos se emepiezan a contar desde 0.
arr[0]

1

In [123]:
# Es posible operar directamente con los elementos.
arr[0] + arr[5]

7

In [124]:
# En el caso de las matrices al indezar una posición se regresa el array de dicha posición.
matriz[0]

array([1, 2, 3])

In [125]:
# Para seleccionar un solo elemento de la matriz se especifica la posición del elemento separada por comas.
matriz[0, 2]

3

In [126]:
# El slicing nos permite extraer varios datos, tiene un comienzo y un final.
# En este ejemplo se está extrayendo datos desde la posición 1 hasta la 5. [1:6].
arr[1:6]

array([2, 3, 4, 5, 6])

In [127]:
# Si no se ingresa el valor de Start se toma el incio como la posición 0.
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [128]:
# En cambio si no se le da una posción de End se regresan todos los elementos hasta el final del array.
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [129]:
# También se puede trabajar por pasos.
# En este ejemplo de 3 en 3.
arr[::3]
# Regresa la posición 0, 0 + 3, 3 + 3 y como no hay posición 6 + 3, no se regrese nada.

array([1, 4, 7])

In [130]:
# Cuando se le asigna un valor negativo se regresan los valores comenzando desde la última posición del array.
arr[-1]

9

In [131]:
arr[-3:]

array([7, 8, 9])

In [132]:
# Para el caso de las matrices sucede algo similar.
# Para acceder a los valores a nivel de filas.
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [133]:
# Para acceder a los valores a nivel de filas y columnas.
matriz[1:, 0:2]

array([[4, 5],
       [7, 8]])

## **🔡Tipos de datos**
Los arrays de NumPy solo pueden contener un tipo de dato, ya que esto es lo que le confiere las ventajas de la optimización de memoria.

In [134]:
# Podemos conocer el tipo de datos del array consultando la propiedad .dtype.
arr = np.array([1, 2, 3, 4])
arr.dtype

dtype('int64')

In [135]:
# Si queremos usar otro tipo de dato lo podemos definir en la declaración del array.
arr = np.array([1, 2, 3, 4], dtype = 'float64')
arr.dtype

dtype('float64')

In [136]:
# Ahora vemos que los valores están con punto decimal.
arr

array([1., 2., 3., 4.])

In [137]:
# Si ya se tiene el array definido se usa el método .astype() para convertir el tipo de dato.
arr = np.array([1, 2, 3, 4])
arr = arr.astype(np.float64)
arr

array([1., 2., 3., 4.])

In [138]:
# También se puede cambiar a tipo booleano recordando que los números diferentes de 0 se convierten en True.
arr = np.array([0, 1, 2, 3, 4])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

In [139]:
# También podemos convertir los datos en tipo string.
arr = np.array([0, 1, 2, 3, 4])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

In [140]:
# De igual forma se puede pasar de string a numero.
arr = np.array(['0', '1', '2', '3', '4'])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)

In [141]:
# Si un elemento no es de tipo número el método falla.
arr = np.array(['hola','0', '1', '2', '3', '4'])
arr = arr.astype(np.int8)
arr

ValueError: ignored

## **🔳Dimensiones**
scalar: dim = 0 Un solo dato o valor

vector: dim = 1 Listas de Python

matriz: dim = 2 Hoja de cálculo

tensor: dim > 3 Series de tiempo o Imágenes

In [142]:
# Declarando un escalar.
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [143]:
# Declarando un vector.
vector = np.array([1, 2, 3])
print(vector)
vector.ndim

[1 2 3]


1

In [144]:
# Declarando una matriz.
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [145]:
# Declarando un tensor.
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],[[13, 13, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 13 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]


3

### Agregar o eliminar dimensiones

In [146]:
# Se puede definir el número de dimensiones desde la declaración del array
vector = np.array([1, 2, 3], ndmin = 10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [147]:
# Se pueden expandir dimensiones a los array ya existentes.
# Axis = 0 hace refencia a las filas, mientras que axis = 1 a las columnas.
expand = np.expand_dims(np.array([1, 2, 3]), axis = 0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [148]:
# Remover/comprimir las dimensiones que no están siendo usadas.
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)


[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


### **Reto**
1. Definir un tensor de 5 dimensiones
2. Sumar una dimensión en algún eje
3. Borrar dimensiones que no se usen

In [149]:
# 1) 
tensor5 = np.array([[[[1, 2],[3, 4]], [[5, 6],[7, 8]]], [[[1, 2],[3, 4]], [[5, 6],[7, 8]]]], ndmin = 5)
print(tensor5, tensor5.ndim)

[[[[[1 2]
    [3 4]]

   [[5 6]
    [7 8]]]


  [[[1 2]
    [3 4]]

   [[5 6]
    [7 8]]]]] 5


In [150]:
# 2)
expand5 = np.expand_dims(tensor5, axis=1)
print(expand5, expand5.ndim)

[[[[[[1 2]
     [3 4]]

    [[5 6]
     [7 8]]]


   [[[1 2]
     [3 4]]

    [[5 6]
     [7 8]]]]]] 6


In [151]:
# 3)
print(expand5, expand5.ndim)
reduced5 = np.squeeze(expand5)
print(reduced5, reduced5.ndim)

[[[[[[1 2]
     [3 4]]

    [[5 6]
     [7 8]]]


   [[[1 2]
     [3 4]]

    [[5 6]
     [7 8]]]]]] 6
[[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]


 [[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]] 4


## **🔀Creando arrays**

In [152]:
# Este métodode NumPy nos permite generar arrays sin definir previamente una lista.
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [153]:
# Un tercer argumento permite definir un tamaño de paso.
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [154]:
# np.zeros() nos permite definir estructuras o esquemas. 
np.zeros(3)

array([0., 0., 0.])

In [155]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [156]:
# De iugal forma tenemos np.ones()
np.ones(3)

array([1., 1., 1.])

In [157]:
# np.linspace() permite generar una arrary definiendo un incio, un final y cuantas divisiones tendrá.
np.linspace(0, 10 , 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [158]:
# También podemos crear una matriz con una diagonal de 1 y el resto de 9.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [159]:
# Otra metódo importante es generar números aleatorios.
np.random.rand()

0.38727363176349083

In [160]:
# También se pueden generar vectores.
np.random.rand(4)

array([0.31353932, 0.46923069, 0.07434372, 0.56868854])

In [161]:
# Y a su vez generar matrices.
np.random.rand(4,4)

array([[0.5948063 , 0.97711458, 0.54407726, 0.92757122],
       [0.42918087, 0.24172444, 0.87240663, 0.4681055 ],
       [0.79023711, 0.03617802, 0.40307162, 0.71838365],
       [0.11898222, 0.78011366, 0.56469773, 0.28840107]])

In [162]:
# NumPy nos permite tambien generar números enteros.
# En este caso números enteros entre el 1 y 14
np.random.randint(1,15)

14

In [163]:
# También podemos llevarlos a una  estructura definida.
np.random.randint(1,15, (3,3))

array([[ 7,  3,  8],
       [11,  2,  8],
       [ 1,  4, 10]])

## **🟦🔹Shape y Reshape**
* Shape me indica la forma del arreglo
* Reshape transforma el arreglo mientras se mantengan los elementos.

In [164]:
arr = np.random.randint(1,10,(3,2))
arr.shape

(3, 2)

In [165]:
arr

array([[4, 6],
       [7, 8],
       [4, 8]])

In [166]:
arr.reshape(1,6)

array([[4, 6, 7, 8, 4, 8]])

In [167]:
arr.reshape(2,3)

array([[4, 6, 7],
       [8, 4, 8]])

In [168]:
np.reshape(arr,(1,6))

array([[4, 6, 7, 8, 4, 8]])

In [169]:
# Se puede hacer un reshape como lo haría C.
np.reshape(arr,(2,3), 'C')

array([[4, 6, 7],
       [8, 4, 8]])

In [170]:
# También se puede hacer reshape a como lo haría Fortran.
np.reshape(arr,(2,3), 'F')

array([[4, 4, 8],
       [7, 6, 8]])

In [171]:
# Además existe la opción de hacer reshape según como esté optimizado nuestro computador. En este caso es como en C.
np.reshape(arr,(2,3), 'A')

array([[4, 6, 7],
       [8, 4, 8]])

### **Reto**
1. Crear un array de cualquier dimesnión y cambiar sus dimensiones
2. Intentar cambiar el array de forma que no respete la estructura original

In [172]:
# 1)
array_original = np.random.randint(0,10, (3,3))
array_original

array([[9, 3, 8],
       [7, 6, 5],
       [0, 7, 5]])

In [173]:
array_original.reshape(1,9)

array([[9, 3, 8, 7, 6, 5, 0, 7, 5]])

In [174]:
# 2)
array_original.reshape(2,4)

ValueError: ignored

## 🧮**Funciones principales de NumPy**

In [175]:
arr = np.random.randint(1, 20, 10)
matriz = arr.reshape(2,5)
matriz

array([[ 6, 18,  2,  6, 13],
       [13, 12,  7, 15, 17]])

In [176]:
arr

array([ 6, 18,  2,  6, 13, 13, 12,  7, 15, 17])

In [177]:
arr.max()

18

In [178]:
matriz.max()

18

In [179]:
# Podemos regresar los máximos de cada fila o columna especificando el eje.
matriz.max(1)

array([18, 17])

In [180]:
matriz.max(0)

array([13, 18,  7, 15, 17])

In [181]:
# tambien tenemos .argmax() que nos devuelve la posición del elemento
arr.argmax()

1

In [182]:
matriz.argmax(0)

array([1, 0, 1, 1, 1])

In [183]:
# De forma análoga tenemos .min()
arr.min()

2

In [184]:
arr.argmin()

2

In [185]:
matriz.min(0)

array([ 6, 12,  2,  6, 13])

In [186]:
matriz.argmin(1)

array([2, 2])

In [187]:
# Podemos saber la diferencia de valor más bajo con el más alto.
arr.ptp() # 18 - 1

16

In [188]:
matriz.ptp(0)

array([7, 6, 5, 9, 4])

In [189]:
# Para hacer análisis estádistico se tienen la siguientes funciones.
# Ordenar los elementos:
arr.sort()
arr 

array([ 2,  6,  6,  7, 12, 13, 13, 15, 17, 18])

In [190]:
# Obtener un percentil:
np.percentile(arr, 0)

2.0

In [191]:
# Mediana:
np.median(arr)

12.5

In [192]:
# Desviación estándar:
np.std(arr)

5.068530358989674

In [193]:
# Varianza:
np.var(arr)

25.689999999999998

In [194]:
# Promedio
np.mean(arr)

10.9

In [195]:
# Lo mismo aplica para las matrices.
np.median(matriz, 1)

array([ 6., 15.])

In [196]:
# Se pueden unir dos arrays por medio de la concatenación
a = np.array([[1,2], [3,4]])
b= np.array([5, 6])

In [197]:
np.concatenate((a,b), axis = 0)

ValueError: ignored

In [198]:
# El error anterior es debido a a tiene 2 dimensiones mientras que b tiene 1.
print(a.ndim)
b.ndim

2


1

In [199]:
b = np.expand_dims(b, axis = 0)
np.concatenate((a,b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [200]:
# De igual forma podemos agregarlo en el otro eje
np.concatenate((a,b), axis = 1)

ValueError: ignored

In [201]:
# Como b es una fila y no una columna, no se puede concatenar a menos que se aplique la transpuesta.
np.concatenate((a,b.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

## **📝Copy**
.copy() nos permite copiar un array de NumPy en otra variable de tal forma que al modificar el nuevo array los cambios no se vean reflejados en array original.

In [202]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [203]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [204]:
trozo_de_arr = arr[0:6]
trozo_de_arr[:] = 0
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

In [205]:
# Se han modificado los datos del array original porque seguía haciendo referencia a esa variable.
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [206]:
arr_copy = arr.copy()
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [207]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])